### ISSUE TITLE
Not working npm 

### ISSUE THREAD

**Issue by omar1779** [BancoGeneral/Boton-de-Pago-Yappy_Node.js#5]
No encuentra npm el packete de yappy o no tengo acceso a ello

**Comment by joseamayadev** [comment]
@omar1779, debes descargarte el paquete porque el repo no lo trae previamente integrado y cuando apuntas a la ruta no existe.
https://github.com/BancoGeneral/Boton-de-Pago-Yappy_Node.js/releases/tag/1.1.2

En el release tienes los paquetes para que te integres con NodeJS y Express. 

Tengo actualmente un pequeño instructivo en mi blog:
https://joseamayadev.com/blog/C%C3%B3mo-integrar-Yappy-Comercial-con-Node-JS/

Espero te funcione, saludos @omar1779

**Comment by omar1779** [comment]
@joseamayadev gracias por la  ayuda de tu Blog , fue muy util 😊
